
version: "3.7"

volumes:
  workingdir: 
    driver: local

services:
  creation-worker:
    container_name: creation-worker
    working_dir: /worker_root/workers
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/..:/worker_root
      - $HOME:$HOME
    environment:
      - TZ=America/New_York
      - RABBITMQ_HOST=root:atx!cloud!scalphunter@api.atlasxomics.com
      - REDIS_HOST=:atx!cloud!scalphunter@api.atlasxomics.com
    command: celery -A creation worker -n creation@${POSTFIX}  -Q creation_worker --concurrency=4 --loglevel=INFO
    
  test-worker:
    container_name: test-worker
    working_dir: /worker_root/workers
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/../:/worker_root
      - $HOME:$HOME
    environment:
      - TZ=America/New_York
      - RABBITMQ_HOST=root:atx!cloud!scalphunter@api.atlasxomics.com
      - REDIS_HOST=:atx!cloud!scalphunter@api.atlasxomics.com
    command: celery -A test worker -n test@${POSTFIX}  -Q atxcloud_test --concurrency=4 --loglevel=INFO

  core-worker:
    container_name: core-worker
    working_dir: /worker_root/workers
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/../:/worker_root
      - $HOME:$HOME
    environment:
      - TZ=America/New_York
      - RABBITMQ_HOST=root:atx!cloud!scalphunter@api.atlasxomics.com
      - REDIS_HOST=:atx!cloud!scalphunter@api.atlasxomics.com
    command: celery -A core worker -n core@${POSTFIX}  -Q atxcloud_core --concurrency=4 --loglevel=INFO

  gene-worker:
    container_name: gene-worker
    working_dir: /worker_root/workers
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/../:/worker_root
      - $HOME:$HOME
    environment:
      - TZ=America/New_York
      - RABBITMQ_HOST=root:atx!cloud!scalphunter@api.atlasxomics.com
      - REDIS_HOST=:atx!cloud!scalphunter@api.atlasxomics.com
    command: celery -A gene worker -n gene@${POSTFIX} -Q atxcloud_gene --concurrency=4 --loglevel=INFO

  atlasbrowser-worker:
    container_name: atlasbrowser-worker
    working_dir: /worker_root/workers
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/..:/worker_root
      - $HOME:$HOME
    environment:
      - TZ=America/New_York
      - RABBITMQ_HOST=root:atx!cloud!scalphunter@api.atlasxomics.com
      - REDIS_HOST=:atx!cloud!scalphunter@api.atlasxomics.com
    command: celery -A atlasbrowser worker -n atlasbrowser@${POSTFIX}  -Q atxcloud_atlasbrowser --concurrency=4 --loglevel=INFO
  webfile-worker:
    container_name: webfile-worker
    working_dir: /worker_root/workers
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/..:/worker_root
      - $HOME:$HOME
    environment:
      - TZ=America/New_York
      - RABBITMQ_HOST=root:atx!cloud!scalphunter@api.atlasxomics.com
      - REDIS_HOST=:atx!cloud!scalphunter@api.atlasxomics.com
      - MYSQL_USERNAME=root
      - MYSQL_HOST=api.atlasxomics.com 
      - MYSQL_DB=dbit_data
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=atx!cloud!pw
    command: celery -A webfile worker -n webfile@${POSTFIX}  -Q atxcloud_webfile --concurrency=4 --loglevel=INFO

  nuclei-worker:
    container_name: nuclei-worker
    working_dir: /worker_root/workers
    # network_mode : host
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/stc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro 
      - $PWD/..:/worker_root
      - $HOME:$HOME
    environment:
      - TZ=America/New_York
      - RABBITMQ_HOST=root:atx!cloud!scalphunter@api.atlasxomics.com
      - REDIS_HOST=:atx!cloud!scalphunter@api.atlasxomics.com
    command: celery -A nuclei worker -n nuclei@${POSTFIX}  -Q atxcloud_nuclei --concurrency=4 --loglevel=INFO